In [1]:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [2]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [4]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=1)

print(newarr)

[  5  10 -20]


In [5]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [6]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [10]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [11]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [12]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


# Pandas

In [15]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2],'Values':[121,321,23]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings  Values
0    BMW         3     121
1  Volvo         7     321
2   Ford         2      23


In [23]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2],'Values':[121,321,23]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings  Values
0    BMW         3     121
1  Volvo         7     321
2   Ford         2      23


In [24]:
import pandas as pd

print(pd.__version__)

1.4.4


In [25]:
import numpy as np

print(np.__version__)

1.21.5


In [28]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [29]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


In [35]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [36]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [37]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [38]:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


In [39]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [40]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


In [47]:
import pandas as pd

df = pd.read_excel('C:\commercial_outlet_data\Status Tenants SEPTEMBER 2023.xlsx',sheet_name='SEPT 2023',skiprows=[0,1,2,3,4])

df.head() 

C:\Users\Mind-Graph\anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():


NO AIRPORT     CATEGORY SUB-CATEGORY      TENANT ID    CONTRACT NO  \
0  1      T1  Convenience          NaN  IS00100014661  2500000000208   
1  2      T1       Retail          NaN  IS00100014491  2500000000204   
2  3      T1     Services        TELCO  IS00100015803  2300000000118   
3  4      T1       Retail    Promotion  IS00100017824  5100000000621   
4  5      T1          F&B          NaN  IS00100016722  2200000000254   

                          CONCESSIONAIRE              LOT NO LOCATION  \
0             7-ELEVEN MALAYSIA SDN BHD    LOT NO. MTB-5-L20  Level 5   
1  GUARDIAN HEALTH AND BEAUTY SDN. BHD.    LOT NO. MTB-5-L13  Level 5   
2                MAXIS BROADBAND SDN BHD  LOT NO. MTB -3-L09  Level 3   
3                 MNL FORTUNE ENTERPRISE          PS-MTB-TA1  Level 5   
4     BERJAYA KRISPY KREME DOUGHNUTS SDN   LOT NO. MTB-5-L21  Level 5   

           TRADE NAME  ...   23   24   25   26   27   28   29   30  PIC  \
0             7Eleven  ...  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  SAB   
1            Guardian  ...  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  SAB   
2               Maxis  ...  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  SAB   
3  Chocolates Beryl's  ...  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  SAB   
4        Krispy Kreme  ...  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  SAB   

                 REMARKS  
0  22 tenant for ops hrs  
1                    NaN  
2                    NaN  
3  01/12/2022-31/05/2023  
4                    NaN  

[5 rows x 45 columns]

In [48]:
df.to_string() 

"      NO AIRPORT     CATEGORY         SUB-CATEGORY      TENANT ID    CONTRACT NO                                   CONCESSIONAIRE                                              LOT NO    LOCATION                                                TRADE NAME   BUILDING               AREA                                                    OPS HRS     1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30    PIC                                          REMARKS\n0      1      T1  Convenience                  NaN  IS00100014661  2500000000208                       7-ELEVEN MALAYSIA SDN BHD                                    LOT NO. MTB-5-L20     Level 5                                                   7Eleven        MTB   PUBLIC CONCOURSE                                                    24 Hours  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.

In [57]:
import pandas as pd
df.display.max_rows

AttributeError: 'DataFrame' object has no attribute 'display'

In [50]:
df.tail()

NO AIRPORT  CATEGORY SUB-CATEGORY      TENANT ID    CONTRACT NO  \
395  /      T1    Retail          NaN  IS00100017252  2500000000270   
396  /      T2    Retail          NaN  IS00100013589  2100000000119   
397  /      T1  Services    Promotion  IS00100017586  5100000000604   
398  /      T1  Services    Promotion            NaN            NaN   
399  /      T1       F&B    Promotion  IS00100018179  5100000000651   

                           CONCESSIONAIRE  \
395  MALAYSIA AIRPORTS (NIAGA) SDN. BHD.    
396             BUY MORE EXPRESS SDN BHD    
397                          Meta Expert    
398                     EY TRAVEL SDN BHD   
399                GIBCA VENTURES SDN BHD   

                                  LOT NO LOCATION            TRADE NAME  ...  \
395  LOT NO. SATP D01, SATELLITEBUILDING      C11  Eraman DF Emporium 1  ...   
396                    LOT NO. S1-1A-A06  Level 1              Soxworld  ...   
397                    LOT NO. MTB-3-L06  Level 3              U Mobile  ...   
398                                  NaN  Level 5             EY Travel  ...   
399                    LOT NO. PS-MTB-02  Level 5      ALHABSHI DESSERT  ...   

     23  24  25  26  27  28  29  30   PIC                 REMARKS  
395 NaN NaN NaN NaN NaN NaN NaN NaN   NaN                     NaN  
396 NaN NaN NaN NaN NaN NaN NaN NaN   NaN   1/7/2022 - 31/12/2022  
397 NaN NaN NaN NaN NaN NaN NaN NaN   NaN  1/10/2022 - 30/09/2024  
398 NaN NaN NaN NaN NaN NaN NaN NaN   NaN                     NaN  
399 NaN NaN NaN NaN NaN NaN NaN NaN  MIRA                     NaN  

[5 rows x 45 columns]

In [52]:
df.max_rows()

AttributeError: 'DataFrame' object has no attribute 'max_rows'