# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

NumPy is a Python library used for working with arrays.

In [4]:
print(np.__version__)

1.21.5


In [5]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
a = np.array(40)

In [7]:
a

array(40)

In [8]:
print(a.ndim)

0


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [18]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [14]:
b = [1, 2, 3 ,4, 5, 6, 7, 8, 9 ,10, 11, 12]

In [19]:
a[0,1]

array([4, 5, 6])

In [1]:
import pandas as pd

In [49]:
df1=pd.read_excel('C:\\Users\\Mind-Graph\\Downloads\\TB_ACTIVE _FLIGHT_COM.xlsx',sheet_name='Sheet1')

In [50]:
df1

AIRCRAFTOPERATORCODE  Unnamed: 1  Unnamed: 2 IATA  Unnamed: 4  Unnamed: 5  \
0                     AK         NaN         NaN   7L         NaN         NaN   
1                     MH         NaN         NaN   8L         NaN         NaN   
2                     FY         NaN         NaN   8M         NaN         NaN   
3                     QR         NaN         NaN   9C         NaN         NaN   
4                     JL         NaN         NaN   BA         NaN         NaN   
..                   ...         ...         ...  ...         ...         ...   
155                   RY         NaN         NaN  NaN         NaN         NaN   
156                  OMD         NaN         NaN  NaN         NaN         NaN   
157                   KR         NaN         NaN  NaN         NaN         NaN   
158                   G2         NaN         NaN  NaN         NaN         NaN   
159                   GR         NaN         NaN  NaN         NaN         NaN   

    Common_Aircraft Different_Aircraft  
0                PK                 DL  
1                NH                 UA  
2                JT                 IU  
3                UL                 UK  
4                TH                RMF  
..              ...                ...  
155             NaN                NaN  
156             NaN                NaN  
157             NaN                NaN  
158             NaN                NaN  
159             NaN                NaN  

[160 rows x 8 columns]

In [51]:
df1.columns

Index(['AIRCRAFTOPERATORCODE', 'Unnamed: 1', 'Unnamed: 2', 'IATA',
       'Unnamed: 4', 'Unnamed: 5', 'Common_Aircraft', 'Different_Aircraft'],
      dtype='object')

In [72]:
df2=pd.read_excel('C:\\Users\\Mind-Graph\\Downloads\\TB_ACTIVE _FLIGHT_COM.xlsx',sheet_name='W21')

In [73]:
df2

IATA
0    BG
1    BR
2    BS
3    CI
4    CV
5    CZ
6    EY
7    FM
8    JL
9    KE
10   KL
11   MF
12   MH
13   RA
14   SV
15   3G
16   3K
17   5J
18   5X
19   BI
20   ET
21   FX
22   GA
23   N7
24   NH
25   PK
26   PR
27   QR
28   SQ
29   TK
30   TR
31   W5
32   WW
33   WY
34   AK
35   EK
36   H9
37   QZ
38   YG
39   Z2
40   OD

In [74]:
set1 = set(df1.Different_Aircraft.unique())

In [75]:
set2 = set(df2.IATA.unique())

In [76]:
common_vals = set1&set2

In [77]:
diff_value = set1 ^ set2

In [78]:
max_length = max(len(common_vals), len(diff_value))
list1 = list(common_vals) + [None] * (max_length - len(common_vals))
list2 = list(diff_value) + [None] * (max_length - len(diff_value))
df_r = pd.DataFrame({'col1': list1, 'col2': list2})

In [79]:
df_r.rename(columns = {'col1':"Common_Values", 'col2' : "Different_values"},inplace = True)

In [80]:
df_r

Common_Values Different_values
0              W5              NaN
1            None               DL
2            None               UA
3            None               IU
4            None               UK
..            ...              ...
130          None               JL
131          None               MH
132          None               PR
133          None               LA
134          None               HA

[135 rows x 2 columns]

In [81]:
df_r.to_excel(r'C:\Users\Mind-Graph\Downloads\Common_different_vals_W21.xlsx')